version: 1.0.2.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
    - master
    - develop
    - feature\/\w.*
  except:
    - task\/\w.*

image: Visual Studio 2017

nuget:
  disable_publish_on_pr: true

configuration: Release

before_build:
  - cmd: nuget restore src/ScriptSharp.sln

build:
  project: src/ScriptSharp.sln
  verbosity: detailed

test: off