version: 1.0.2.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
    - feature/Build-Modernisation

image: Visual Studio 2017

nuget:
  disable_publish_on_pr: true

configuration: Release

before_build:
  - cmd: mkdir src/Output/Packages
  - cmd: nuget restore src/DSharp.sln

build:
  project: src/DSharp.sln
  verbosity: detailed
