name: .NET Core

on:
  push:
    branches: [ master, feature/github-actions ]
  pull_request:
    branches: [ master, feature/github-actions ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ".\src\DSharp.sln"
    - name: Build
      run: dotnet build ".\src\DSharp.sln" --configuration Release --no-restore
    - name: Test Compiler
      run: dotnet test ".\src\DSharp.Compiler\DSharp.Compiler.csproj" --no-restore --verbosity normal
    - name: Test CodeAnalysis
      run: dotnet test ".\src\DSharp.CodeAnalysis.Test\DSharp.CodeAnalysis.Test.csproj" --no-restore --verbosity normal
